#ifndef SYSTEM_STATE_H
#define SYSTEM_STATE_H

typedef enum
{
    SYSTEM_STATE_STOPPED = 0,
    SYSTEM_STATE_STARTING, 
    SYSTEM_STATE_RUNNING,
    SYSTEM_STATE_ESTOP_BRAKING,
    SYSTEM_STATE_FAULT_LATCHED
} SystemState_t;

#endif /* SYSTEM_STATE_H */
